"""Protocol constants, one per quantitative statement of Section 2 of the paper.

Each constant cites the section/equation that fixes it. Where the paper text does not give the value, the comment says
which choice was adopted. No other module should contain a "loose" protocol number: everything comes from here.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import platform
import sys

# text output always in UTF-8 (the Windows console uses cp1252 and breaks on characters such as "≈")
for _f in (sys.stdout, sys.stderr):
    try:
        _f.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# --------------------------------------------------------------------------- paths
SRC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # <repository>/src
ROOT = os.path.dirname(SRC)  # repository root
BASE = ROOT
DATA = os.environ.get("A4_DATA_DIR", os.path.join(ROOT, "data"))  # input data (see data/README.md)
VAL = os.path.join(os.environ.get("A4_OUTPUT_DIR", os.path.join(ROOT, "output")), "validation")
A4_OUT = os.path.join(VAL, "reliability")
A4_CACHE_FOOT = os.path.join(A4_OUT, "foot_cache")
A4_CACHE_THORAX = os.path.join(A4_OUT, "thorax_cache")
A4_RESULTS = os.path.join(A4_OUT, "results")
A4_LOGS = os.path.join(A4_OUT, "logs")
A4_SMOKE = os.path.join(A4_OUT, "_smoke")
FOOT_DATASET = os.path.join(DATA, "foot")
FOOT_METADATA = os.path.join(FOOT_DATASET, "metadata.csv")
FOOT_FOLDER = os.path.join(FOOT_DATASET, "foot")
RPLHR_PAIRS = os.path.join(DATA, "rplhr", "pairs_val_test.json")  # generated by scripts/prepare_rplhr.py
FOOT_LIST_N48 = os.path.join(A4_OUT, "foot_list_n48.json")
FOOT_LIST_N48_OLD = os.path.join(VAL, "list_n48.json")  # optional; only for verification

# --------------------------------------------------------------------------- §2.2 cohorts
N_FEET = 48  # §2.2.1 "48 distinct feet were retained"
SZ_FOOT_MM = 0.5  # §2.2.1 "original through-plane slice thickness of 0.5 mm"
PIXEL_FOOT_MM = (
    0.88,
    1.37,
)  # §2.2.1 "in-plane pixel spacing ranging from approximately 0.88 to 1.37 mm"
N_THORAX = 150  # §2.2.2 "150 thoracic cases"
N_THORAX_VAL, N_THORAX_TEST = 50, 100  # §2.2.2 "50 validation cases and 100 test cases"
R36_PARTITION = "test"  # the validation was used in the SR selection -> §3.6 on the 100 test cases
PIXEL_THORAX_MM = 0.7  # §2.2.2 "An in-plane spacing of 0.7 mm was therefore adopted"
DZ_THIN_THORAX_MM, DZ_THICK_THORAX_MM = (
    1.0,
    5.0,
)  # §2.2.2 "5-mm... input... 1-mm... reference"
HU_RPLHR_A, HU_RPLHR_B = (
    3072.0,
    -1024.0,
)  # §2.2.2 "converted back to HU using the original intensity interval":
# files normalized to [0,1] from [-1024, 2048] HU -> HU = 3072 v - 1024.
# SOURCE OF THE INTERVAL: the README of the RPLHR-CT repository does not state the normalization (read on
# 2026-09-12; % verify the formal source with the author). INTERNAL EVIDENCE (a4_data --window-hu,
# results/window_hu_rplhr.json): the soft-tissue mode in the raw values is v = 0.347 in
# 12/12 cases -> 42 HU with [-1024, 2048] (soft tissue/blood) and 397 HU with [-1024, 3071]
# (impossible). The [-1024, 2048] window is confirmed by measurement; see also
# rplhr_pairs_consistency.json (floor 0 and ceiling 1 reached: fixed window with clipping).
R_PAIRS_EXPECTED = 0.999  # §2.2.2 "intensity correlation of approximately r = 0.999"

# --------------------------------------------------------------------------- §2.3 thick slice
K_FOOT = 6  # §2.3, Eq. 1 "k = 6"
# Eq. 2: Δz_thick = k · Δz_HR = 6 × 0.5 = 3.0 mm (verified by assertion in a4_cohort)

# --------------------------------------------------------------------------- §2.4 super-resolution
SR_CHANNELS = 48  # §2.4 "48 feature channels per layer"
SR_CONV_LAYERS = 10  # §2.4 "10 convolutional residual layers" (1 input + 8 body + 1 output = VDSRlite(ch=48, n=8))
SR_BODY_N = 8  # §2.4: 10 layers = 1 input + 8 body + 1 output (derived from "10 convolutional residual layers")
SR_PATCH = 48  # §2.4 "48 × 48 pixels"
SR_BATCH = 16  # §2.4 "batch size of 16"
# Learning rate and iterations SELECTED by HEBO (20 evaluations, RPLHR-CT validation, n = 50) and adopted by the
# rule fixed a priori (smallest objective among the 20 and the published one): evaluation 19, objective 1.0686 mm
# vs 1.0764 for the published one (paired per case: -0.0009 mm, 29/50, p = 0.33). Value published in §2.4: 1e-3
# and 2500 (sr_selection/sr_config.PUBLISHED_SR). Source: results/sr_selection_hebo.json.
SR_LR = 0.0005850631055477961  # (text: 5.85e-4); §2.4 published 1e-3
SR_ITERS = 3046  # §2.4 published 2500
SR_SEED_EVALUATED = (
    0  # seed of the evaluated network (text silent; declared)
)
SR_VAL_FRAC = 0.0  # §2.8.2 requires "432 image slices" in the prior and §2.4
# "patches extracted from the available volume"; no slice is held out §2.4 does NOT describe intensity
# normalization; the reading without additions is to train on raw HU ("hu": lo = 0, esc = 1). Declared
# alternatives: "minmax" (volume extremes, no parameter) and "percentiles" (previous reading, with clipping). The
# choice between "hu" and "minmax" was fixed by an a priori criterion (L1 loss decreases without NaN and the final
# loss in HU is <= 2x that of the scaled version). RESULT of that
# check: criterion met on both feet, with LOWER final loss in raw HU (z001: 25.4 vs
# 34.5 HU; z002: 23.4 vs 31.9 HU; no NaN) -> "hu" fixed.
SR_NORMALIZATION = "hu"
SR_NORM_PERCENTILES = (
    0.5,
    99.9,
)  # normalization by percentiles of the thick volume, with clipping to [0,1];
# the clipping does not reach the 200 HU threshold (the 99.9th percentile is well above it)
SR_DEGRADATION_DK = "decimation"  # D_k of Eq. 3 = subsampling by spacing k (decimation); alternative "area"
SR_DEGRADATION_UK = "linear"  # U_k of Eq. 3 = LINEAR reinterpolation (the same kernel as the trilinear baseline); alternative "bicubic"
SR_ORIENTATIONS = (
    "yz",
    "xz",
)  # §2.4 "reconstructed orthogonal sections were subsequently combined" (mean of the two)
SR_DEVICE = (
    "cuda"  # §2.4 "performed on an NVIDIA GeForce GTX 1660 Ti GPU" (mandatory)
)

# --------------------------------------------------------------------------- §2.5 segmentation and mesh
BONE_THRESHOLD_HU = 200.0  # §2.5 "fixed attenuation threshold of 200 HU"
CLEANING_CLOSING_ITER = (
    2  # "morphological cleaning" = binary closing x2
)
CLEANING_MIN_MM3 = 50.0  # removal of components < 50 mm3
CLEANING_FILL_CAVITIES = False  # cavity filling REMOVED — not cited in §2.5 and removable (previous reading
# = True). Declared consequence: endosteal surfaces enter the reference and the reconstructions (Eq. 5 measures the
# distance to the nearest sampled point, which in thin cortex can be endosteal).
MESH_MIN_COMPONENT_FACES = 0  # mesh component filter REMOVED (0 = off). §2.5 does not
# describe any operation after marching cubes besides Taubin and decimation, and the filter left the reference
# with more components than the reconstructions (2 vs 1 in the foot; 12 vs 11 in the thorax). The connected-component
# analysis of the text is done in voxels (< 50 mm3 + thick ROI).
GAUSS_MM = 0.8  # §2.5 "isotropic Gaussian kernel with a characteristic scale of 0.8 mm"
MARCHING_CUBES_METHOD = (
    "lorensen"  # §2.5 [28] Lorensen & Cline; skimage default would be 'lewiner'
)
MARCHING_CUBES_LEVEL = 0.5  # level 0.5 = boundary of the smoothed binary mask (text silent; natural symmetric choice)
TAUBIN_ITER = 12  # §2.5 "12 iterations of Taubin smoothing" = 12 COMPLETE iterations (λ step + ν step, Taubin 1995)
TAUBIN_HALF_STEPS = (
    2 * TAUBIN_ITER
)  # trimesh counts each half step as an "iteration" -> 24
TAUBIN_LAMBDA, TAUBIN_NU = (
    0.5,
    0.5,
)  # trimesh defaults; measured -0.008 % of volume
# in 12 it. vs -5.0 % for the Laplacian. The condition in the trimesh docstring
# (0 < 1/λ − 1/ν < 0.1) is violated in the strict sense; choice supported by the measurement.
TARGET_FACES = 60000  # §2.5 "decimated to approximately 60,000 triangular faces"
PADDING_VOXELS = 0  # no caps (padding removed; not cited in §2.5). The surfaces stay open where the volume
# cuts the bone, in the reference and in the reconstructions alike (previous reading: 2 voxels; displacement removed)
SINTERP_MASK = "cleaning"  # §2.7.2 "THE bone mask obtained from the original thick-slice volume" —
# the definite article refers to the bone mask that §2.5 defines (200 HU threshold + "morphological cleaning" +
# "connected-component analysis... excluding disconnected objects unrelated to the target anatomy"), applied on
# the thick grid: closing x2, < 50 mm3, soft-tissue ROI; WITHOUT cavities (CLEANING_FILL_CAVITIES) and WITHOUT cap
# (SINTERP_CAP). Alternative "threshold" : pure threshold, 141-151 components in S_interp, x6 loses power
# (isolated rho 0.313 -> 0.202). Implemented in a4_features.thick_mask_sinterp. DECLARED CONSEQUENCE:
# CLEANING_CLOSING_ITER counts voxels of the mask grid; on the thick grid the closing reaches 2·k·Δz in z (foot 6
# mm, thorax 10 mm) against 1 mm on the thin grid. §2.5 does not give the scale in mm ("the same thresholding and
# post-processing sequence"); reading: same sequence in voxels. Effect measured per case in
# meta["cleaning"]["s_interp"] (voxels added by the closing, components removed, ROI clipping).
SINTERP_CAP = False  # no cap on S_interp (consistent with PADDING_VOXELS = 0; before: 1 thick voxel)
DECIMATION_TOLERANCE = (
    0.10  # "approximately 60,000": accepts [0.9, 1.1] x target
)
# "connected-component analysis... excluding disconnected objects unrelated to the target
# anatomy" implemented as a soft-tissue ROI of the THICK volume: air threshold -300 HU, binary opening (1 it.),
# largest connected component, ISOTROPIC dilation in mm (the MESH component filter was removed, §2.5
# applies the CCA to the binary mask, before "before mesh extraction").
ROI_AR_HU = -300.0  # air threshold of the soft-tissue ROI (text silent)
ROI_OPENING_ITER = (
    1  # binary opening of 1 iteration before the largest component
)
ROI_DILATE_MM = 3.0  # isotropic in mm (before: 6 voxels of the thin grid = 3 mm in z, ~6 mm in-plane)

# --------------------------------------------------------------------------- §2.6 error per vertex
N_REFERENCE_POINTS = 120000  # §2.6 "120,000 points were uniformly sampled"
# Target definition. "sampled": Eq. 5 of the reference run (distance to the nearest sampled point; carries a
# sampling floor of about 0.36 mm, see supplement/exact_error.py). "exact": distance from the vertex to the reference
# surface itself (point to triangle), bounded by the sampled distance; vertices farther than EXACT_MAX_MM from the
# sampled points keep the sampled value (mesh artefacts).
ERROR_DEFINITION = "exact"
EXACT_MAX_MM = 20.0
EXACT_LARGE_TRIANGLE_MM = 5.0
# Vertices outside the CT volume (detached fragments of the mesh) are removed from every per-vertex array of the case
# before it is saved (margin in mm around the grid box).
REMOVE_VERTICES_OUTSIDE_VOLUME = True
OUTSIDE_VOLUME_MARGIN_MM = 1.0
# sampling seed derived from the case identifier (text silent)

# --------------------------------------------------------------------------- §2.7 features and forest
N_FEATURES = 9  # §2.7, Eq. 7 "x(v) ∈ R^9"
FEATURE_NAMES = [
    "nz_abs",
    "d_f",
    "angular_defect",
    "roughness",
    "nz_abs_x_d_f",
    "d_shape",
    "delta_z",
    "t_slice",
    "delta_xy",
]  # Eq. 8–14, in order
ROUGHNESS_ITER = 3  # Eq. 11 "three iterations of Laplacian smoothing"
ROUGHNESS_LAMBDA = 0.5  # Eq. 11 "λ = 0.5"
# delta_z = through-plane spacing of the RECONSTRUCTED GRID (0.5 mm foot; 1.0 mm thorax); t_slice = k·Δz
RF_PARAMS = dict(
    n_estimators=200, max_depth=8, min_samples_leaf=50, max_features=3
)  # §2.7.3 "200 trees, max depth 8, min 50 samples per leaf"
# revised: §2.7.3 "decision trees trained under randomized sampling and feature-selection procedures [36]" — with
# max_features=1.0 (sklearn default, value of the historical runs) there is NO random selection of variables. The
# text does not fix the number; for p = 9 the three canonical rules coincide: p/3 = 3 (regression; default mtry of
# the randomForest package, Liaw & Wiener 2002 — the attribution to Breiman 2001 [36] stays "% verify"), sqrt(9) =
# 3 and int(log2 9) = 3. Consequence: all numbers of §3.2–3.7 change relative to the historical runs (Abstract).
RF_SEED = 0  # forest seed (text silent; declared)
# NESTED selection of the forest hyperparameters inside the LOO (§2.7.4). "fixed" = RF_PARAMS above; "nested" =
# a4_optimize_rf.nested_lofo. Design fixed a priori: RF_SEARCH space (min_samples_leaf as a FRACTION of the
# training samples, so that it holds equally in the search with RF_SEARCH_N_VERTICES per case and in the refit
# with N_TRAIN_PER_CASE), RF_SEARCH_FOLDS inner folds per case, objective = median of the per-case Spearman rho of
# the inner validation, TPE (Optuna) with seed 0 + index of the outer fold.
RF_SELECTION = "nested"
RF_SEARCH = dict(
    n_estimators=(100, 400, 50),  # (min, max, step)
    max_depth=(4, 14),
    leaf_frac=(
        1e-4,
        2e-2,
    ),  # log-uniform; 50/188000 = 2.66e-4 (value of the text) is inside
    max_features=(1, N_FEATURES),
)
RF_SEARCH_FOLDS = 4  # inner folds per case (deterministic partition i mod k by the order of the identifiers);
# 4 = value of the document (the protocol)
# was aligned to the document BEFORE any run
RF_SEARCH_N_VERTICES = 1000  # vertices per training case DURING the search (final refit: N_TRAIN_PER_CASE)
RF_SEARCH_TRIALS_FOOT = 40
RF_SEARCH_TRIALS_THORAX = 20  # cost: 150 outer folds
RF_SEARCH_STARTUP = 10  # initial random attempts of the TPE
RF_SEARCH_SAMPLER = (
    "tpe"  # "random" = control of sensitivity to the optimizer (same budget)
)
RF_ABLATION_REUSE_SELECTION = True  # §2.10: isolated/reduced models use, per fold, the configuration of the full model
# Declared code rules: min_samples_leaf = max(1, round(leaf_frac x n_samples)); in the
# ablation max_features = min(selected max_features, number of columns of the model). Forest seed = RF_SEED in
# all attempts (paired noise across configurations). Inner-validation subsample = the N_TRAIN_PER_CASE
# vertices of the case (identifier seed), reused in all outer folds.
N_TRAIN_PER_CASE = (
    4000  # §2.7.4 "Up to 4,000 vertices were sampled from each training foot"
)
CONSTANT_OVER = "full_surfaces"  # §2.9.4 e_const = (1/N_-i) Σ_{j≠i} Σ_{u∈S_j} e_j(u) — sum over
# ALL vertices of the training surfaces S_j; alternative "sample_training" (the 4000 drawn)

# --------------------------------------------------------------------------- §2.8 uncertainties
ENS_M = 5  # §2.8.1 "five additional reconstruction networks" (M = 5)
ENS_S = 4  # §2.8.1 "four stochastic forward passes" (S = 4)
ENS_DROPOUT_P = 0.1  # §2.8.1 "dropout probability p = 0.1"
ENS_SEEDS = (
    100,
    101,
    102,
    103,
    104,
)  # seeds of the members (text silent; declared)
ENS_MEMBER_MC = 0  # §2.8.1 "a single trained network" for u_MC (Eq. 25): member 1 (index 0); same for Eq. 34
ENS_DROPENS_DDOF = (
    1  # Eq. 26 "SD" with the same sample divisor as Eq. 23 and 25
)
# the network is 2D; "stochastic forward pass" = pass per plane, with a dropout mask per plane and per orientation
DS_MASK_SCALE = False  # Eq. 28 "θ_t = m_t ⊙ θ, m_t binary mask" — without 1/(1-p) scaling; True = historical variant
DS_EWC_MODE = "probe_and_restart"  # probe of DS_EWC_ITER_CALIBRATION it. to fix lambda, then full adaptation
# with lambda from it. 0 ("regularized by an EWC penalty"); alternative "after_calibration"
DS_PRIOR_ITERS = 6000  # §2.8.2 "trained for 6000 iterations"
DS_PRIOR_LR = 1e-3  # §2.8.2 does not give the prior learning rate; until then it was inherited from
# SR_LR (1e-3). The selection applies to the PER-CASE network of §2.4 (and to the ensemble members of §2.8.1,
# which are repeated reconstructions of it), not to the dense prior over the pool of 36 feet: the prior keeps 1e-3.
DS_PRIOR_SLICES_PER_FOOT = 12  # §2.8.2 "432 image slices obtained from 36 feet" = 36 × 12
DS_PARTITIONS = 4  # §2.8.2 "divided into four partitions"
DS_SUBNETS = 5  # §2.8.2 "Five subnetworks"
DS_REFINEMENT_ITERS = 600  # §2.8.2 "adapted... for 600 iterations"
DS_REFINEMENT_LR = 2e-4  # §2.8.2 "learning rate of 2e-4"
DS_EWC_FRACTION = 0.10  # §2.8.2 "approximately 10% of the data-fitting loss"
DS_EWC_ITER_CALIBRATION = 50  # §2.8.2 "after approximately 50 adaptation iterations"
DS_FISHER_BATCHES = (
    100  # Fisher diagonal estimated on 100 batches of the prior pool
)
DS_EWC_TOLERANCE = (
    0.10  # relative tolerance of the penalty/loss ratio at t = 50 (10 % of 10 %)
)
DS_EWC_MAX_PROBES = 14  # maximum number of regularized calibration probes (bracketing + bisection)
DS_EWC_FACTOR_MIN = 3.0  # minimum growth of lambda per probe while the ratio does not cross the target
# with the real prior (6000 it.) the penalty/loss ratio at t = 50 is NOT monotonic in lambda (rises to ~0.03–0.07,
# drops into a valley near 1e8 and rises again to 0.10 near 1e9–1e10); the pure proportional adjustment got stuck
# in the valley (5 of 10 subnetworks without converging). The search became: geometric growth (factor
# max(FACTOR_MIN, target/ratio)) until crossing the target, then bisection in log(lambda) between the largest
# lambda below and the smallest lambda above the target. The criterion of the text is the same (~10 % in ~50 it.).
ENS_PASSES_SEED_BASE = (
    1000  # seed of pass s of member m = 1000*(m+1) + s
)
UNCERTAINTY_DDOF = 1  # sample divisor in Eq. 23, 25, 26, 30, 32, 34
DS_PRIOR_SEED_BASE = (
    500  # seeds (500 + partition; subnetworks 7000 + 31·t), declared
)
DS_SUBNET_SEED_BASE, DS_SUBNET_SEED_STEP = (
    7000,
    31,
)  # seeds of the fixed masks of the subnetworks (7000 + 31 t; text silent)

# --------------------------------------------------------------------------- §2.9 evaluation
K_REGIONS = 25  # §2.9.2 "K = 25"
KMEANS_N_INIT, KMEANS_SEED = (
    4,
    0,
)  # Lloyd via sklearn.KMeans(n_init=4, random_state=0)
DECILE_FRACTION = (
    0.10  # §2.9.3 "upper decile" / "10% of vertices with the largest predicted values"
)
N_CALIBRATION_DECILES = 10  # §2.9.4 "ten equally populated groups"

# --------------------------------------------------------------------------- §2.11 registration
REG_K = 200  # §2.11 "K = 200 surface correspondences"
REG_TRIALS = 300  # §2.11 "300 repeated registration trials"
REG_TARGET_PERCENTILE = 80  # §2.11 "distance exceeding the 80th percentile"
REG_SELECTION_QUANTILE = (
    0.20  # draw among the 20 % of smallest value (field, d_shape, oracle)
)
REG_SELECTION = "kmeans"  # reading without a parameter not cited — "regions" = the 25 k-means regions of §2.9.2 (Eq. 36-37)
# computed on the evaluated surface; the strategy selects the region of LOWEST mean of the criterion ("lowest");
# each of the 300 trials draws K = 200 correspondences WITHIN the region ("correspondences were sampled from the
# selected region"; "independently sampled correspondence sets"); random ("random SURFACE selection") draws one
# VERTEX uniformly on the surface per trial and uses the region that contains it ( alternative: draw one of the 25
# regions with equal probability); global unchanged; target beyond the p80 of the distance to the REGION. Previous
# alternatives: "region_mean" (200 neighbors, 20 %) and "vertex". REG_SELECTION = "region_mean" # §2.11 "selected
# REGIONS with the lowest predicted geometric error" / "regions with the lowest measured error": the selected
# object is the region; its error = mean of the criterion over the K vertices of the region (200 neighbors of the
# center). A center is drawn among those whose regions are in the 20 % of lowest mean. Alternative "vertex"
# (previous code): center drawn among the 20 % of vertices of lowest pointwise value.
REG_GLOBAL_N = REG_K  # global condition with K = 200 correspondences on the whole surface
# ("K = 200 surface correspondences were used" precedes the list of strategies); alternative 4K = 800
REG_TARGET_MODE = "region"  # "separated from the registration region by a distance exceeding the 80th percentile of the
# within-surface distance distribution" = distribution of the distances of ALL vertices of the surface to the
# registration REGION; target drawn among those that exceed the 80th percentile. The reading "single threshold per
# case (80th percentile of the pairwise distances)" proved INFEASIBLE in the smoke test: central regions have no
# vertex beyond the threshold. Alternative "center": distances to the center of the region (old code). region =
# the K nearest neighbors of the center (all used); "independently sampled correspondence sets" realized by
# redrawing the center at each trial
REG_STRATEGIES = (
    "field",
    "d_shape",
    "random",
    "oracle",
    "global",
)  # §2.11: exactly five
REG_SEED = 0  # seed of the trials (declared)

# --------------------------------------------------------------------------- §2.12 statistics
ALPHA = 0.05  # §2.12 "adjusted p < 0.05"
# two-sided paired Wilcoxon + Benjamini–Hochberg; summary by median and IQR (no bootstrap)


def ensure_folders():
    for d in (A4_OUT, A4_CACHE_FOOT, A4_CACHE_THORAX, A4_RESULTS, A4_LOGS, A4_SMOKE):
        os.makedirs(d, exist_ok=True)


def code_hash() -> str:
    """Concatenated SHA-256 of the .py files of the reliability package (traceability of the outputs)."""
    h = hashlib.sha256()
    folder = os.path.dirname(os.path.abspath(__file__))
    for f in sorted(os.listdir(folder)):
        if f.endswith(".py"):
            h.update(f.encode())
            h.update(open(os.path.join(folder, f), "rb").read())
    return h.hexdigest()[:16]


def _sr_origin() -> dict:
    """Provenance of SR_LR/SR_ITERS: selection file, sha256, adopted evaluation."""
    p = os.path.join(A4_RESULTS, "sr_selection_hebo.json")
    if not os.path.exists(p):
        return {"file": None}
    with open(p, "rb") as f:
        dig = hashlib.sha256(f.read()).hexdigest()
    with open(p, encoding="utf-8") as f:
        a = json.load(f)["summary"]["adopted"]
    return {
        "file": "results/sr_selection_hebo.json",
        "sha256": dig,
        "adopted_index": a.get("index"),
        "adopted_equals_a4_config": (a["lr"], a["iters"]) == (SR_LR, SR_ITERS),
    }


def environment_record(with_torch: bool = True) -> dict:
    """Metadata written in every cache and JSON: versions, pick_device, date, code hash."""
    import numpy
    import scipy
    import SimpleITK
    import skimage
    import sklearn
    import trimesh

    reg = {
        "data": datetime.datetime.now().isoformat(timespec="seconds"),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "numpy": numpy.__version__,
        "scipy": scipy.__version__,
        "sklearn": sklearn.__version__,
        "skimage": skimage.__version__,
        "trimesh": trimesh.__version__,
        "SimpleITK": SimpleITK.Version_VersionString(),
        "code_hash_reliability": code_hash(),
        "sr_lr": SR_LR,
        "sr_iters": SR_ITERS,
        "ds_prior_lr": DS_PRIOR_LR,
        "sr_origin": _sr_origin(),
    }
    try:
        import fast_simplification

        reg["fast_simplification"] = fast_simplification.__version__
    except Exception:
        reg["fast_simplification"] = None
    try:
        import optuna

        reg["optuna"] = (
            optuna.__version__
        )  # the TPE trajectory depends on the version
    except Exception:
        reg["optuna"] = None
    if with_torch:
        import torch

        reg["torch"] = torch.__version__
        reg["cuda_available"] = bool(torch.cuda.is_available())
        reg["gpu"] = (
            torch.cuda.get_device_name(0) if torch.cuda.is_available() else None
        )
    return reg
