"""Closed-value tests for the equations that the coverage table (COVERAGE_EQUATIONS_2026-09-16.md) flagged as
"check only": Eq. 19 (mean of the T = 200 trees and hyperparameters), Eq. 24 (mean inside the variance accumulator),
Eq. 35 (Spearman per case), Eq. 38–39 (regional means), Eq. 47–50 (ablation: isolated, reduced and Δ per case)
and Eq. 4 (L1 objective = mean absolute error). Outside the package hash (subfolder tests/)."""

from __future__ import annotations

import os
import sys

import numpy as np

sys.path.insert(
    0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
from reliability import a4_config as C  # noqa: E402
from reliability import a4_statistics as E  # noqa: E402


def _data(n_cases=3, n=300, seed=0):
    rng = np.random.default_rng(seed)
    F, e = {}, {}
    for i in range(n_cases):
        X = rng.normal(size=(n, C.N_FEATURES)).astype(np.float32)
        F["c%d" % i] = X
        e["c%d" % i] = (
            0.5 + 0.8 * X[:, 5] + 0.3 * X[:, 2] + 0.1 * rng.normal(size=n)
        ).astype(np.float32)
    return F, e


def test_eq19_tree_mean_and_hyperparameters():
    """Eq. 19: e^(v) = (1/T) Σ_t h_t(x(v)), T = 200; §2.7.3: depth 8, 50 samples per leaf."""
    F, e = _data()
    X = np.vstack(list(F.values()))
    y = np.concatenate(list(e.values()))
    mdl = E.forest().fit(X, y)
    p = mdl.get_params()
    assert (
        p["n_estimators"] == 200
        and p["max_depth"] == 8
        and p["min_samples_leaf"] == 50
        and p["max_features"] == 3
    )
    assert len(mdl.estimators_) == 200
    Xq = X[:50]
    tree_mean = np.mean([t.predict(Xq) for t in mdl.estimators_], axis=0)
    assert np.allclose(mdl.predict(Xq), tree_mean, atol=1e-10)


def test_eq24_accumulator_mean_and_sd():
    """Eq. 22–24: the map accumulator returns the mean (Eq. 22/24) and the sample standard deviation (Eq. 23,
divisor M−1)."""
    from reliability.a4_uncertainty import _Accum

    rng = np.random.default_rng(1)
    maps = rng.normal(size=(5, 4, 3, 2))
    ac = _Accum(maps.shape[1:])
    for m in maps:
        ac.add(m)
    assert np.allclose(ac.mean(), maps.mean(axis=0), atol=1e-12)
    assert np.allclose(ac.sd(1), maps.std(axis=0, ddof=1), atol=1e-10)
    assert np.allclose(ac.sd(0), maps.std(axis=0, ddof=0), atol=1e-10)


def test_eq35_spearman_closed_form_value():
    """Eq. 35: Spearman ρ per case — monotonically increasing = 1, decreasing = −1, closed value with a tie."""
    a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    assert abs(E.spearman(a, a**3) - 1.0) < 1e-12
    assert abs(E.spearman(a, -a) + 1.0) < 1e-12
    # ranks: a = 1..5; b = [1, 3, 2, 5, 4] -> d² = 0+1+1+1+1 = 4 -> ρ = 1 − 6·4/(5·24) = 0.8
    b = np.array([10.0, 30.0, 20.0, 50.0, 40.0])
    assert abs(E.spearman(a, b) - 0.8) < 1e-12


def test_eq38_39_regional_means():
    """Eq. 38–39: mean of e (or e^) over the vertices of each region k = 1..K."""
    lab = np.array([0, 0, 1, 2, 2, 2])
    x = np.array([1.0, 3.0, 5.0, 1.0, 2.0, 3.0])
    assert np.allclose(E.regional_means(x, lab, K=3), [2.0, 5.0, 2.0])


def test_eq47_50_isolated_reduced_ablation_and_delta():
    """Eq. 47 (a single feature), Eq. 48–49 (without feature j) and Eq. 50 (Δ_ij = ρ_full − ρ_−j per case):
 with e generated by x6 (+ x3), removing x6 reduces ρ and the isolated one of x6 exceeds that of a noise column."""
    F, e = _data(n_cases=3, n=400)
    full = E.lofo(F, e, n_training=400)
    iso6 = E.lofo(F, e, columns=[5], n_training=400)  # Eq. 47, j = 6
    iso1 = E.lofo(F, e, columns=[1], n_training=400)  # Eq. 47, j = 2 (noise)
    without6 = E.lofo(
        F, e, columns=[c for c in range(9) if c != 5], n_training=400
    )  # Eq. 48–49
    for h in F:
        rho_full = E.spearman(full[h][0], e[h])
        delta = rho_full - E.spearman(without6[h][0], e[h])  # Eq. 50
        assert delta > 0.2, (h, delta)
        assert E.spearman(iso6[h][0], e[h]) > 0.5 > E.spearman(iso1[h][0], e[h]) + 0.3
        assert full[h][0].shape == (400,) and without6[h][0].shape == (400,)


def test_eq4_l1_objective_is_mean_absolute_error():
    """Eq. 4: L_SR = mean absolute error; the criterion used in a4_sr is nn.L1Loss (reduction 'mean')."""
    import torch

    from reliability import a4_sr as SR

    assert "L1Loss" in open(SR.__file__, encoding="utf-8").read()
    a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
    b = torch.tensor([[1.5, 2.0], [2.0, 4.0]])
    assert abs(float(torch.nn.L1Loss()(a, b)) - (0.5 + 0.0 + 1.0 + 0.0) / 4) < 1e-7
